import Autocomplete from "./Autocomplete.vue";
import ButtonDropdown from "./ButtonDropdown.vue";
import Chart from "./Chart.vue";
import ChartPanel from "./ChartPanel.vue";
import DataTable from "./DataTable.vue";
import DatePicker from "./DatePicker.vue";
import Draggable from "./Draggable.vue";
import Grid from "./Grid.vue";
import GridItem from "./GridItem.vue";
import JsonEditor from "./JsonEditor.vue";
import JsonEditorIaf from "./JsonEditorIaf.vue";
import JsonEditorView from "./JsonEditorView.vue";
import JsonEditorViewArray from "./JsonEditorViewArray.vue";
import Moment from "./Moment.vue";
import Notifications from "./Notifications.vue";
import Overlay from "./Overlay.vue";
import Pagination from "./Pagination.vue";
import Password from "./Password.vue";
import PdfViewer from "./PdfViewer.vue";
import TreeView from "./TreeView.vue";
import TreeViewItem from "./TreeViewItem.vue";
import UploadUserPhoto from "./UploadUserPhoto.vue";

Vue.component("latte-autocomplete", Autocomplete);
Vue.component("latte-button-dropdown", ButtonDropdown);
Vue.component("latte-chart", Chart);
Vue.component("latte-chart-panel", ChartPanel);
Vue.component("latte-data-table", DataTable);
Vue.component("latte-datepicker", DatePicker);
Vue.component("latte-draggable", Draggable);
Vue.component("latte-grid", Grid);
Vue.component("latte-grid-item", GridItem);
Vue.component("latte-json-editor", JsonEditor);
Vue.component("latte-json-editor-iaf", JsonEditorIaf);
Vue.component("latte-json-editor-view", JsonEditorView);
Vue.component("latte-json-editor-view-array", JsonEditorViewArray);
Vue.component("latte-moment", Moment);
Vue.component("latte-notifications", Notifications);
Vue.component("latte-overlay", Overlay);
Vue.component("latte-pagination", Pagination);
Vue.component("latte-password", Password);
Vue.component("latte-pdf-viewer", PdfViewer);
Vue.component("latte-tree-view", TreeView);
Vue.component("latte-tree-view-item", TreeViewItem);
Vue.component("latte-upload-user-photo", UploadUserPhoto);
